language: cpp
script: make; make install ; cd test ; make; ls 
addons:
  apt:
    packages:
    - tcl
    - tcl-dev
    - tk
    - tk-dev
    - libreadline5
    - libboost-graph-dev
    - exuberant-ctags
    - libdb-dev
